#  You are given the following DNA sequence:

# AAACGCTGTCAATACAATCTTYCTAGATATTCGGATTTGAA
# TTTTGCAAAAAGTCCGAAGCTGCCCACCTCAAGTCATTGTT
# TCAACTCGCTTACGGTATATATATCTACTTTCATTGAGATA
# TAAACAGCGCTGATACAATCTTTTTATATAAGTCTTTTGTA
# CAAATAAAGCTAGGAAAAGCCCGACGTCATTATAGCTAT

# An imaginary restriction enzyme cuts in "AAGTCA" find
# where in the previous sequence this enzyme will cut


dna = 'AAACGCTGTCAATACAATCTTYCTAGATATTCGGATTTGAATTTTGCAAAAAGTCCGAAGCTGCCCACCTCAAGTCATTGTTTCAACTCGCTTACGGTATATATATCTACTTTCATTGAGATATAAACAGCGCTGATACAATCTTTTTATATAAGTCTTTTGTACAAATAAAGCTAGGAAAAGCCCGACGTCATTATAGCTAT'
index = dna.find('AAGTCA')
print(f'{dna[0:index]} - {dna[index:len(dna)]}')
